VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = no
MUSIC_ENABLE = no

# Space saving settings
# VIA_ENABLE = yes
# VIAL_ENABLE = yes
# LTO_ENABLE = yes
# QMK_SETTINGS = yes
# EXTRAKEY_ENABLE = yes
# MOUSEKEY_ENABLE = yes

# CONSOLE_ENABLE = no
# COMMAND_ENABLE = no

# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no
# MAGIC_ENABLE = no
# AVR_USE_MINIMAL_PRINTF = yes
# MUSIC_ENABLE = no
