VIA_ENABLE = yes
VIAL_ENABLE = yes
COMBO_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes

MUSIC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
VIALRGB_ENABLE = no
BACKLIGHT_ENABLE = no
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
MIDI_ENABLE = no
