name: Build Keymap

on:
  push:
    branches:
      - vial
  pull_request:
    branches:
      - vial
  workflow_dispatch:
    inputs:
      keymap:
        description: 'Keymap to build'
        required: true
        default: 'vial'
jobs:
  build:
    uses: ./.github/workflows/ci_build_major_branch_keymap.yml
    with:
      branch: ${{ github.ref_name }}
      keymap: noys
      slice_length: '5'
