name: Build Keymap

on:
  push:
    branches:
      - vial
  pull_request:
    branches:
      - vial

jobs:
  build:
    uses: ./.github/workflows/ci-build-major-branch-keymap.yml
    with:
      branch: ${{ github.ref_name }}
      keymap: noys
      slice_length: '5'
